/**
 * \file  sysClk_config.h
 * \brief This file is used to configure a system clock
 */

#ifndef __EPCF_INCLUDED_PERIPHERAL_SYSCLK_SYSCLK_CONFIG_H
#define __EPCF_INCLUDED_PERIPHERAL_SYSCLK_SYSCLK_CONFIG_H

#include "sysClk.h"

#define __EPCF_SYSCLK_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EPCF_DIR_NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/include/,sysClk/sysClk_,PCF_ARCH_DEVICE.h)
#include __EPCF_SYSCLK_INCLUDE
#undef __EPCF_SYSCLK_INCLUDE

/*
#if(EPCF_BUILD_MODE == EPCF_BUILD_NATIVE)
	#if(EPCF_USE_SYSCLK == PCF_YES)
		#define __EPCF_SYSCLK_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/sysClk/,sysClk_,PCF_ARCH_DEVICE.h)
		#include __EPCF_SYSCLK_INCLUDE
		#undef __EPCF_SYSCLK_INCLUDE
	#endif
#endif

#if(EPCF_BUILD_MODE == EPCF_BUILD_EXTENDED)
	#if(EPCF_EXTENDED_USE_SYSCLK == PCF_YES)
		/// NO Extended controller for SysClock
	#endif
	#if(EPCF_USE_SYSCLK == PCF_YES)
		#define __EPCF_SYSCLK_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/sysClk/,sysClk_,PCF_ARCH_DEVICE.h)
		#include __EPCF_SYSCLK_INCLUDE
		#undef __EPCF_SYSCLK_INCLUDE
	#endif
#endif
*/
#endif      //__EPCF_INCLUDED_PERIPHERAL_SYSCLK_SYSCLK_CONFIG_H
