/**
 * \file  wdt_config.h
 * \brief This file is used to configure a Watchdog timer device
 */

#ifndef __EPCF_INCLUDE_PERIPHERAL_WDT_WDT_CONFIG_H
#define __EPCF_INCLUDE_PERIPHERAL_WDT_WDT_CONFIG_H

#include "wdt.h"

#define __EPCF_WDT_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EPCF_DIR_NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/include/wdt/,wdt_,PCF_ARCH_DEVICE.h)
#include __EPCF_WDT_INCLUDE
#undef __EPCF_WDT_INCLUDE

/*
#if(EPCF_BUILD_MODE == EPCF_BUILD_NATIVE)
	#if(EPCF_USE_WDT == PCF_YES)
		#define EPCF_WDT_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/wdt/,wdt_,PCF_ARCH_DEVICE.h)
		#include EPCF_WDT_INCLUDE
		#undef EPCF_WDT_INCLUDE
	#endif
#endif

#if(EPCF_BUILD_MODE == EPCF_BUILD_EXTENDED)
	#if(EPCF_USE_WDT == PCF_YES)
		#define EPCF_WDT_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/wdt/,wdt_,PCF_ARCH_DEVICE.h)
		#include EPCF_WDT_INCLUDE
		#undef EPCF_WDT_INCLUDE
	#endif

	#if(EPCF_EXTENDED_USE_WDT == PCF_YES)
		#define EPCF_WDT_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EXTENDED_PATH/,controller/,wdt/,wdt_controller.h)
		#include EPCF_WDT_INCLUDE
		#undef EPCF_WDT_INCLUDE
	#endif
#endif*/

#endif      //__EPCF_INCLUDE_PERIPHERAL_WDT_WDT_CONFIG_H
