/**
 * \file  adc_config.h
 * \brief This file is used to configure a ADC device
 */

#ifndef __EPCF_PERIPHERAL_INCLUDE_ADC_ADC_CONFIG_H
#define __EPCF_PERIPHERAL_INCLUDE_ADC_ADC_CONFIG_H

#include "adc.h"

#define __EPCF_ADC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EPCF_DIR_NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/include/adc/,adc_,PCF_ARCH_DEVICE.h)
#include __EPCF_ADC_INCLUDE
#undef __EPCF_ADC_INCLUDE

/*
#if(EPCF_BUILD_MODE == EPCF_BUILD_NATIVE)
	#if(EPCF_USE_ADC == PCF_YES)
		#define __EPCF_ADC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/adc/,adc_,PCF_ARCH_DEVICE.h)
		#include __EPCF_ADC_INCLUDE
		#undef __EPCF_ADC_INCLUDE
	#endif
#endif

#if(EPCF_BUILD_MODE == EPCF_BUILD_EXTENDED)
	#if(EPCF_USE_ADC == PCF_YES)
		#define __EPCF_ADC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/adc/,adc_,PCF_ARCH_DEVICE.h)
		#include __EPCF_ADC_INCLUDE
		#undef __EPCF_ADC_INCLUDE
	#endif

	#if(EPCF_EXTENDED_USE_ADC == PCF_YES)
		#define __EPCF_ADC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EXTENDED_PATH/,controller/,adc/,adc_controller.h)
		#include __EPCF_ADC_INCLUDE
		#undef __EPCF_ADC_INCLUDE
	#endif
#endif
*/

#endif      //__EPCF_PERIPHERAL_INCLUDE_ADC_ADC_CONFIG_H
