/**
 * \file  rtc_config.h
 * \brief This file is used to configure a RTC device
 */

#ifndef __EPCF_INCLUDED_PERIPHERAL_RTC_RTC_CONFIG_H
#define __EPCF_INCLUDED_PERIPHERAL_RTC_RTC_CONFIG_H

#include "rtc.h"

#if(EPCF_BUILD_MODE == EPCF_BUILD_NATIVE)
	#if(EPCF_USE_RTC == PCF_YES)
		#define __EPCF_RTC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/rtc/,rtc_,PCF_ARCH_DEVICE.h)
		#include __EPCF_RTC_INCLUDE
		#undef __EPCF_RTC_INCLUDE
	#endif
#endif

#if(EPCF_BUILD_MODE == EPCF_BUILD_EXTENDED)
	#if(EPCF_USE_RTC == PCF_YES)
		#define __EPCF_RTC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/rtc/,rtc_,PCF_ARCH_DEVICE.h)
		#include __EPCF_RTC_INCLUDE
		#undef __EPCF_RTC_INCLUDE
	#endif

	#if(EPCF_EXTENDED_USE_RTC == PCF_YES)
		#define __EPCF_RTC_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EXTENDED_PATH/,controller/,rtc/,rtc_controller.h)
		#include __EPCF_RTC_INCLUDE
		#undef __EPCF_RTC_INCLUDE
	#endif
#endif

#endif      //__EPCF_INCLUDED_PERIPHERAL_RTC_RTC_CONFIG_H
