/**
 * \file  i2c_config.h
 * \brief This file is used to configure a I2C device
 */

#ifndef __EPCF_PERIPHERAL_INCLUDE_I2C_I2C_CONFIG_H
#define __EPCF_PERIPHERAL_INCLUDE_I2C_I2C_CONFIG_H

#include "i2c.h"

#define __EPCF_I2C_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EPCF_DIR_NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/include/i2c/,i2c_,PCF_ARCH_DEVICE.h)
#include __EPCF_I2C_INCLUDE
#undef __EPCF_I2C_INCLUDE

/*
#if(EPCF_BUILD_MODE == EPCF_BUILD_NATIVE)
    #if(EPCF_USE_I2C == PCF_YES)
        #define __EPCF_I2C_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/i2c/,i2c_,PCF_ARCH_DEVICE.h)
        #include __EPCF_I2C_INCLUDE
        #undef __EPCF_I2C_INCLUDE
    #endif
#endif

#if(EPCF_BUILD_MODE == EPCF_BUILD_EXTENDED)
    #if(EPCF_USE_I2C == PCF_YES)
        #define __EPCF_I2C_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(NATIVE_PATH/,port/PCF_ARCH_NAME/PCF_ARCH_VARIANT/PCF_ARCH_DEVICE_VENDOR/PCF_ARCH_DEVICE/i2c/,i2c_,PCF_ARCH_DEVICE.h)
        #include __EPCF_I2C_INCLUDE
        #undef __EPCF_I2C_INCLUDE
    #endif

    #if(EPCF_EXTENDED_USE_I2C == PCF_YES)
        #define __EPCF_I2C_INCLUDE PCF_CONDITIONAL_INCLUDE_FILE(EXTENDED_PATH/,controller/,i2c/,i2c_controller.h)
        #include __EPCF_I2C_INCLUDE
        #undef __EPCF_I2C_INCLUDE
    #endif
#endif
*/

#endif      //__EPCF_PERIPHERAL_INCLUDE_I2C_I2C_CONFIG_H
